# 네트워크 설정
network:
  # PC IP 주소
  wonho_pc: "192.168.0.15"     # 원호 PC (rosGui)
  chaeyeon_pc: "192.168.0.21"  # 채연 PC (AI Server)
  beomjin_pc: "192.168.0.75"   # 범진 PC

  wonho_pc: "192.168.0.15"     
  chaeyeon_pc: "192.168.0.15"  
  beomjin_pc: "192.168.0.75"   

# AI 서버 설정
ai_server:
  ip: "127.0.0.1"
  port: 5005
  max_packet_size: 60000
  
  # AI 서버 관련 포트들
  udp_port: 5005      # UDP 이미지 전송용
  status_port: 5006   # 상태 정보 전송용

  target_central_server:
    ip: "127.0.0.1"
    port: 5005 

# Central 서버 설정
central_server:
  udp_receive_port: 5005

  ip: "127.0.0.1"
  port: 6000
  
  # HTTP 서버 (웹 API용)
  http_port: 8080
  http_host: "0.0.0.0"
  
  # ROS2 통신용
  ros_port: 6006
  
  # GUI 통신용
  gui_port: 6007

  target_ros_gui:
    ip: "127.0.0.1"
    port: 8888

ros_gui_client:
  ip: "127.0.0.1"
  udp_receive_port: 8888 # UDP 이미지를 받을 포트
  display_port: 8888 

database:
  host: "localhost"
  port: 3306
  username: "root"
  password: "0000"
  database: "HeroDB"